# Problem name: Finding the Difference
# Description: Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s=list(s)
        s.sort()
        t=list(t)
        t.sort()
        for i in range(len(t)):
            if(i>len(s)-1):
                return t[-1]
            elif(t[i]!=s[i]):
                return t[i]